const createClient=window.supabase && window.supabase.createClient;
if(!createClient)throw new Error('Supabase library failed to load.');
const SUPABASE_URL='https://uinhyjqsqrgfczqrmcya.supabase.co';
const SUPABASE_KEY='sb_publishable_qmrBMbSlLInIYT2IXwy49Q_WnMiToQJ';
const VAPID_PUBLIC_KEY='BJRhrsTFFybj-5P4yPXxjGRMuiukrdE1ywD9cVaGXv6H7kAyCBU6bF4sP6LXozkyjmQXyJ51FWSM2exqAjPSl_s';
const supabase=createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
window.atdSupabase=supabase;
const $=id=>document.getElementById(id);
const state={user:null,settings:null,bets:[],selectedPlayer:null,searchTimer:null};
const authView=$('authView'),appView=$('appView'),authForm=$('authForm'),authMessage=$('authMessage'),betForm=$('betForm'),playerInput=$('playerInput'),playerResults=$('playerResults'),selectedPlayerBox=$('selectedPlayer'),betMessage=$('betMessage');
function money(v){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(v||0))}
function odds(v){const n=Number(v);return Number.isFinite(n)?`${n>0?'+':''}${n}`:''}
function potentialProfit(stake,americanOdds){const s=Number(stake||0),o=Number(americanOdds||0);if(!s||!o)return 0;return o>0?s*(o/100):s*(100/Math.abs(o))}
function dateTime(v){if(!v)return'—';return new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZone:'America/New_York'}).format(new Date(v))}
function setMessage(el,text='',type=''){el.textContent=text;el.className=`message ${type}`.trim()}
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function urlBase64ToUint8Array(base64String){const padding='='.repeat((4-base64String.length%4)%4);const base64=(base64String+padding).replace(/-/g,'+').replace(/_/g,'/');const raw=atob(base64);return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)))}
function currentNFLWeek(now=new Date()){const parts=new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(now);const get=t=>Number(parts.find(p=>p.type===t)?.value);const today=Date.UTC(get('year'),get('month')-1,get('day'));const week2Start=Date.UTC(2026,8,15);return Math.max(1,Math.min(18,2+Math.floor((today-week2Start)/(7*86400000))))}
function populateWeeks(){const options=Array.from({length:18},(_,i)=>`<option value="${i+1}">Week ${i+1}</option>`).join('');$('betWeek').innerHTML=options;$('weekFilter').innerHTML=`<option value="all">All Weeks</option>${options}`;$('betWeek').value=String(currentNFLWeek())}
async function updateNotificationStatus(){const el=$('notificationStatus'),btn=$('enableNotificationsBtn');if(!el||!btn)return;if(!('serviceWorker'in navigator)||!('PushManager'in window)||!('Notification'in window)){btn.disabled=true;setMessage(el,'Push notifications are not supported in this browser.','error');return}try{const reg=await navigator.serviceWorker.getRegistration('./');const sub=reg?await reg.pushManager.getSubscription():null;if(sub&&Notification.permission==='granted'){btn.textContent='Hit Alerts Enabled';setMessage(el,'Touchdown alerts are enabled on this device.','success')}else{btn.textContent='Enable Hit Alerts';if(Notification.permission==='denied')setMessage(el,'Notifications are blocked in iPhone Settings for ATD Tracker.','error');else setMessage(el,'Alerts are not enabled on this device.','')}}catch{setMessage(el,'Alerts are not enabled on this device.','')}}
async function enableNotifications(){const btn=$('enableNotificationsBtn'),el=$('notificationStatus');btn.disabled=true;setMessage(el,'Setting up touchdown alerts…');try{if(!('serviceWorker'in navigator)||!('PushManager'in window)||!('Notification'in window))throw new Error('Push notifications are not supported on this device.');const permission=await Notification.requestPermission();if(permission!=='granted')throw new Error('Notification permission was not allowed.');const reg=await navigator.serviceWorker.register('./sw.js');await navigator.serviceWorker.ready;let sub=await reg.pushManager.getSubscription();if(!sub){sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:urlBase64ToUint8Array(VAPID_PUBLIC_KEY)})}const json=sub.toJSON();const{data,error}=await supabase.functions.invoke('atd-push-subscribe',{body:{subscription:{endpoint:json.endpoint,keys:json.keys}}});if(error)throw error;if(data?.error)throw new Error(data.error);const{error:settingsError}=await supabase.from('atd_settings').update({notification_config:json,updated_at:new Date().toISOString()}).eq('user_id',state.user.id);if(settingsError)throw settingsError;state.settings={...state.settings,notification_config:json};btn.textContent='Hit Alerts Enabled';setMessage(el,'Touchdown alerts are enabled on this iPhone.','success')}catch(err){setMessage(el,err.message||'Could not enable notifications.','error')}finally{btn.disabled=false}}
async function init(){populateWeeks();const{data:{session},error}=await supabase.auth.getSession();if(error)console.error('Session error',error);if(session?.user){await enterApp(session.user)}else{showAuth()}supabase.auth.onAuthStateChange((event,s)=>{setTimeout(async()=>{if(s?.user){if(s.user.id!==state.user?.id||appView.classList.contains('hidden'))await enterApp(s.user);return}if(event==='SIGNED_OUT')showAuth()},0)})}
function showAuth(){state.user=null;authView.classList.remove('hidden');appView.classList.add('hidden');authView.style.display='';appView.style.display=''}
async function enterApp(user){state.user=user;authView.classList.add('hidden');appView.classList.remove('hidden');authView.style.display='none';appView.style.display='block';try{await ensureSettings();await loadBets();scheduleOpenAppRefresh();await updateNotificationStatus()}catch(err){console.error('App load error',err);setMessage(authMessage,err.message||'Could not load tracker.','error')}}
async function ensureSettings(){const{data,error}=await supabase.from('atd_settings').select('*').eq('user_id',state.user.id).maybeSingle();if(error)throw error;if(data)state.settings=data;else{const{data:created,error:createError}=await supabase.from('atd_settings').insert({user_id:state.user.id,default_stake:5,season:2026,season_type:2}).select().single();if(createError)throw createError;state.settings=created}$('defaultStake').value=state.settings.default_stake;$('season').value=state.settings.season}
async function loadBets(){const{data,error}=await supabase.from('atd_bets').select('*').order('created_at',{ascending:false});if(error)throw error;state.bets=data||[];renderAll()}
function filteredBets(){const w=$('weekFilter').value;return w==='all'?state.bets:state.bets.filter(b=>String(b.week)===w)}
function renderAll(){renderStats();const filtered=filteredBets();renderDashboardBetList('pendingBets',filtered.filter(b=>b.result==='Pending'));renderDashboardBetList('finishedBets',filtered.filter(b=>b.result!=='Pending'));const all=$('allBets');if(all)renderBetList('allBets',state.bets);const count=$('betCount');if(count)count.textContent=`${state.bets.length} total`}
function renderStats(){const bets=filteredBets(),wins=bets.filter(b=>b.result==='Won').length,losses=bets.filter(b=>b.result==='Lost').length,pendingBets=bets.filter(b=>b.result==='Pending'),pending=pendingBets.length,staked=bets.reduce((s,b)=>s+Number(b.stake||0),0),potential=pendingBets.reduce((s,b)=>s+potentialProfit(b.stake,b.american_odds),0),pl=bets.reduce((s,b)=>s+Number(b.actual_pl||0),0),graded=bets.filter(b=>['Won','Lost'].includes(b.result)).reduce((s,b)=>s+Number(b.stake||0),0),roi=graded?(pl/graded)*100:0;$('statBets').textContent=bets.length;$('statRecord').textContent=`${wins}-${losses}`;$('statStaked').textContent=money(staked);$('statPotential').textContent=money(potential);$('statPL').textContent=money(pl);$('statPL').className=pl>0?'positive':pl<0?'negative':'';$('statROI').textContent=`${roi.toFixed(1)}%`;$('statROI').className=roi>0?'positive':roi<0?'negative':'';$('statPending').textContent=pending}
function renderDashboardBetList(id,bets){const t=$(id);if(!t)return;if(!bets.length){t.innerHTML=`<div class="dashboard-empty">No ${id==='pendingBets'?'pending':'finished'} bets.</div>`;return}t.innerHTML=bets.map(b=>`<details class="dash-bet"><summary><div class="dash-bet-main"><strong>${escapeHtml(b.player_name)}</strong><span>${escapeHtml(b.team||'—')} vs ${escapeHtml(b.opponent||'—')} · ${odds(b.american_odds)}${Number(b.touchdown_target||1)===2?' · 2 TD':''}</span></div><div class="dash-bet-right"><span class="badge ${b.result}">${b.result}</span>${b.result==='Pending'?`<button type="button" class="dash-delete delete-bet" data-id="${b.id}" aria-label="Delete ${escapeHtml(b.player_name)} bet" title="Delete bet"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M9 3h6l1 2h4v2H4V5h4l1-2Zm-2 6h10l-1 12H8L7 9Zm3 2v8h2v-8h-2Zm4 0v8h2v-8h-2Z"/></svg></button>`:''}<span class="dash-chevron">›</span></div></summary><div class="dash-bet-detail"><div><span>Week</span><strong>${b.week}</strong></div><div><span>Stake</span><strong>${money(b.stake)}</strong></div><div><span>Potential</span><strong>${money(potentialProfit(b.stake,b.american_odds))}</strong></div><div><span>P/L</span><strong class="${Number(b.actual_pl)>0?'positive':Number(b.actual_pl)<0?'negative':''}">${money(b.actual_pl)}</strong></div><p>${dateTime(b.game_date)} · ${escapeHtml(b.game_status||'Pending')}</p>${b.result!=='Pending'&&b.result!=='Void'?'<button type="button" class="text-btn refund-bet" data-id="'+b.id+'">Mark Refunded</button>':''}</div></details>`).join('')}
function renderBetList(id,bets){const t=$(id);if(!t)return;if(!bets.length){t.innerHTML='<div class="empty">No bets yet.</div>';return}t.innerHTML=bets.map(b=>`<article class="bet-card"><div class="bet-top"><div><div class="bet-player">${escapeHtml(b.player_name)}</div><div class="bet-meta">Week ${b.week} · ${escapeHtml(b.team||'—')} vs ${escapeHtml(b.opponent||'—')} · ${dateTime(b.game_date)}</div><div class="bet-meta">${escapeHtml(b.game_status||'Pending')}</div></div><span class="badge ${b.result}">${b.result}</span></div><div class="bet-bottom"><div><span>Odds</span><strong>${odds(b.american_odds)}</strong></div><div><span>Stake</span><strong>${money(b.stake)}</strong></div><div><span>Potential Profit</span><strong>${money(potentialProfit(b.stake,b.american_odds))}</strong></div><div><span>P/L</span><strong class="${Number(b.actual_pl)>0?'positive':Number(b.actual_pl)<0?'negative':''}">${money(b.actual_pl)}</strong></div></div><div class="bet-actions">${b.result==='Pending'&&b.game_id?`<button class="text-btn refresh-one" data-id="${b.id}">Refresh</button>`:''}<button class="text-btn danger delete-bet" data-id="${b.id}">Delete</button></div></article>`).join('')}
async function searchPlayers(q){const{data,error}=await supabase.functions.invoke('atd-nfl',{body:{action:'searchPlayers',query:q}});if(error)throw error;if(data?.error)throw new Error(data.error);return data?.players||[]}
playerInput.addEventListener('input',()=>{state.selectedPlayer=null;selectedPlayerBox.classList.add('hidden');clearTimeout(state.searchTimer);const q=playerInput.value.trim();if(q.length<2){playerResults.classList.add('hidden');playerResults.innerHTML='';return}state.searchTimer=setTimeout(async()=>{try{const players=await searchPlayers(q);playerResults.innerHTML=players.length?players.map(p=>`<button type="button" class="search-item" data-player-id="${escapeHtml(p.playerId)}" data-name="${escapeHtml(p.name)}" data-team="${escapeHtml(p.team)}"><span><strong>${escapeHtml(p.name)}</strong><span>${escapeHtml(p.position||'')}</span></span><strong>${escapeHtml(p.team)}</strong></button>`).join(''):'<div class="empty">No players found.</div>';playerResults.classList.remove('hidden')}catch(e){setMessage(betMessage,e.message||'Player search failed.','error')}},350)});
playerResults.addEventListener('click',e=>{const btn=e.target.closest('.search-item');if(!btn)return;state.selectedPlayer={playerId:btn.dataset.playerId,name:btn.dataset.name,team:btn.dataset.team};playerInput.value=state.selectedPlayer.name;selectedPlayerBox.textContent=`${state.selectedPlayer.name} · ${state.selectedPlayer.team}`;selectedPlayerBox.classList.remove('hidden');playerResults.classList.add('hidden')});
$('bulkToggleBtn')?.addEventListener('click',()=>{$('bulkEntryBox').classList.toggle('hidden')});
$('bulkAddBtn')?.addEventListener('click',async()=>{const btn=$('bulkAddBtn'),msg=$('bulkMessage'),week=Number($('betWeek').value),lines=$('bulkBets').value.split(/\\n/).map(x=>x.trim()).filter(Boolean);if(!lines.length)return setMessage(msg,'Paste at least one bet.','error');const parsed=[];for(let i=0;i<lines.length;i++){const p=lines[i].split('|').map(x=>x.trim());if(p.length<3||!p[0]||!Number(p[1])||!Number(p[2]))return setMessage(msg,\`Line ${i+1} should be: Player | Odds | Stake\`,'error');parsed.push({name:p[0],odds:Number(p[1]),stake:Number(p[2])})}btn.disabled=true;let added=0;const failed=[];try{for(let i=0;i<parsed.length;i++){const b=parsed[i];setMessage(msg,\`Adding ${i+1} of ${parsed.length}: ${b.name}…\`);try{const players=await searchPlayers(b.name),player=players.find(p=>p.name.toLowerCase()===b.name.toLowerCase())||players[0];if(!player)throw new Error('Player not found');const{data:lookup,error:fnError}=await supabase.functions.invoke('atd-nfl',{body:{action:'lookupBet',week,playerName:player.name,playerId:player.playerId,season:state.settings.season,seasonType:state.settings.season_type}});if(fnError)throw fnError;if(lookup?.error)throw new Error(lookup.error);const payload={user_id:state.user.id,week,player_name:lookup.name,player_id:lookup.playerId,team:lookup.team,opponent:lookup.opponent,game_date:lookup.gameDate,game_id:lookup.gameId,american_odds:b.odds,stake:b.stake,touchdown_target:1,result:'Pending',game_status:lookup.gameStatus||'Scheduled'};const{error}=await supabase.from('atd_bets').insert(payload);if(error)throw error;added++}catch(err){failed.push(\`${b.name}: ${err.message||'failed'}\`)}}await loadBets();if(!failed.length){$('bulkBets').value='';setMessage(msg,\`Added all ${added} bets successfully.\`,'success')}else setMessage(msg,\`Added ${added} of ${parsed.length}. Failed: ${failed.join('; ')}\`,'error')}finally{btn.disabled=false}});
betForm.addEventListener('submit',async e=>{e.preventDefault();setMessage(betMessage,'Looking up matchup…');$('addBetBtn').disabled=true;try{if(!state.selectedPlayer)throw new Error('Choose a player from the search results.');const week=Number($('betWeek').value),americanOdds=Number($('betOdds').value),stakeOverride=$('betStake').value.trim(),stake=stakeOverride===''?Number(state.settings.default_stake):Number(stakeOverride),touchdownTarget=$('twoTdToggle')?.checked?2:1;if(!americanOdds)throw new Error('Enter American odds such as +180 or -110.');if(!Number.isFinite(stake)||stake<=0)throw new Error('Stake must be greater than $0.');const{data:lookup,error:fnError}=await supabase.functions.invoke('atd-nfl',{body:{action:'lookupBet',week,playerName:state.selectedPlayer.name,playerId:state.selectedPlayer.playerId,season:state.settings.season,seasonType:state.settings.season_type}});if(fnError)throw fnError;if(lookup?.error)throw new Error(lookup.error);const payload={user_id:state.user.id,week,player_name:lookup.name,player_id:lookup.playerId,team:lookup.team,opponent:lookup.opponent,game_date:lookup.gameDate,game_id:lookup.gameId,american_odds:americanOdds,stake,touchdown_target:touchdownTarget,result:'Pending',game_status:lookup.gameStatus||'Scheduled'};const{error}=await supabase.from('atd_bets').insert(payload);if(error)throw error;betForm.reset();state.selectedPlayer=null;selectedPlayerBox.classList.add('hidden');$('betWeek').value=String(currentNFLWeek());setMessage(betMessage,`${lookup.name}: ${touchdownTarget===2?'2 TD':'Anytime TD'} · ${lookup.team} vs ${lookup.opponent} added at ${money(stake)} to win ${money(potentialProfit(stake,americanOdds))}.`,'success');await loadBets()}catch(err){setMessage(betMessage,err.message||'Could not add bet.','error')}finally{$('addBetBtn').disabled=false}});
async function refreshBet(bet){const{data,error}=await supabase.functions.invoke('atd-live',{body:{playerName:bet.player_name,gameId:bet.game_id,touchdownTarget:Number(bet.touchdown_target||1)}});if(error)throw error;if(data?.error)throw new Error(data.error);const{error:updateError}=await supabase.from('atd_bets').update({touchdowns:data.touchdowns,result:data.result,game_status:data.gameStatus,updated_at:new Date().toISOString()}).eq('id',bet.id);if(updateError)throw updateError}
async function refreshPending(){const pending=state.bets.filter(b=>b.result==='Pending'&&b.game_id);if(!pending.length)return;const refreshBtn=$('refreshBtn');if(refreshBtn)refreshBtn.disabled=true;try{for(const bet of pending){try{await refreshBet(bet)}catch(e){console.warn('Refresh failed',bet.player_name,e)}}await loadBets()}finally{if(refreshBtn)refreshBtn.disabled=false}}
function scheduleOpenAppRefresh(){clearInterval(window.__atdRefreshTimer);window.__atdRefreshTimer=setInterval(()=>{if(!document.hidden&&state.user)loadBets()},120000)}
$('refreshBtn')?.addEventListener('click',refreshPending);
$('weekFilter').addEventListener('change',renderAll);
$('enableNotificationsBtn').addEventListener('click',enableNotifications);
document.addEventListener('click',async e=>{const del=e.target.closest('.delete-bet');if(del){e.preventDefault();e.stopPropagation();if(!confirm('Delete this bet?'))return;const{error}=await supabase.from('atd_bets').delete().eq('id',del.dataset.id);if(!error)await loadBets()}const refund=e.target.closest('.refund-bet');if(refund){e.preventDefault();e.stopPropagation();if(!confirm('Mark this bet as refunded? Its P/L will become $0.00 and it will be excluded from your win/loss record and ROI.'))return;const{error}=await supabase.from('atd_bets').update({result:'Void',game_status:'Refunded',updated_at:new Date().toISOString()}).eq('id',refund.dataset.id);if(!error)await loadBets();return}const ref=e.target.closest('.refresh-one');if(ref){const bet=state.bets.find(b=>String(b.id)===String(ref.dataset.id));if(bet){await refreshBet(bet);await loadBets()}}});
$('settingsForm').addEventListener('submit',async e=>{e.preventDefault();const payload={default_stake:Number($('defaultStake').value),season:Number($('season').value),updated_at:new Date().toISOString()};const{data,error}=await supabase.from('atd_settings').update(payload).eq('user_id',state.user.id).select().single();if(error)setMessage($('settingsMessage'),error.message,'error');else{state.settings=data;setMessage($('settingsMessage'),'Settings saved.','success')}});
async function signIn(){setMessage(authMessage,'Signing in…');const btn=$('loginBtn');btn.disabled=true;try{const{data,error}=await supabase.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error)throw error;if(data?.user)await enterApp(data.user);setMessage(authMessage,'','success')}catch(err){setMessage(authMessage,err.message||'Sign in failed.','error')}finally{btn.disabled=false}}
authForm.addEventListener('submit',e=>{e.preventDefault();signIn()});
$('loginBtn').addEventListener('click',signIn);
$('forgotPasswordBtn')?.addEventListener('click',async()=>{const email=$('email').value.trim();if(!email){alert('Enter your email address first, then tap Forgot Password.');return}const btn=$('forgotPasswordBtn');btn.disabled=true;btn.textContent='Sending…';setMessage(authMessage,'Sending password reset email…');try{const{error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:'https://scott12585.github.io/ATD-Tracker/'});if(error)throw error;setMessage(authMessage,'Password reset email sent. Check your inbox.','success');alert('Password reset email sent. Check your inbox and spam folder.')}catch(err){setMessage(authMessage,err.message||'Could not send reset email.','error');alert(err.message||'Could not send reset email.')}finally{btn.disabled=false;btn.textContent='Forgot Password?'}});
$('signupBtn').addEventListener('click',async()=>{setMessage(authMessage,'Creating account…');const{data,error}=await supabase.auth.signUp({email:$('email').value.trim(),password:$('password').value});if(error)return setMessage(authMessage,error.message,'error');setMessage(authMessage,data.session?'Account created.':'Account created. Check your email if confirmation is required.','success')});
$('signOutBtn').addEventListener('click',()=>supabase.auth.signOut());
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&state.user)loadBets()});
init().catch(err=>setMessage(authMessage,err.message||'Startup failed.','error'));