import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.57.4/+esm';
const SUPABASE_URL='https://uinhyjqsqrgfczqrmcya.supabase.co';
const SUPABASE_KEY='sb_publishable_qmrBMbSlLInIYT2IXwy49Q_WnMiToQJ';
const VAPID_PUBLIC_KEY='BJRhrsTFFybj-5P4yPXxjGRMuiukrdE1ywD9cVaGXv6H7kAyCBU6bF4sP6LXozkyjmQXyJ51FWSM2exqAjPSl_s';
const supabase=createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true}});
const $=id=>document.getElementById(id);
const state={user:null,settings:null,bets:[],selectedPlayer:null,searchTimer:null};
const authView=$('authView'),appView=$('appView'),authForm=$('authForm'),authMessage=$('authMessage'),betForm=$('betForm'),playerInput=$('playerInput'),playerResults=$('playerResults'),selectedPlayerBox=$('selectedPlayer'),betMessage=$('betMessage');
function money(v){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(v||0))}
function odds(v){const n=Number(v);return Number.isFinite(n)?`${n>0?'+':''}${n}`:''}
function potentialProfit(stake,americanOdds){const s=Number(stake||0),o=Number(americanOdds||0);if(!s||!o)return 0;return o>0?s*(o/100):s*(100/Math.abs(o))}
function dateTime(v){if(!v)return'—';return new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZone:'America/New_York'}).format(new Date(v))}
function setMessage(el,text='',type=''){el.textContent=text;el.className=`message ${type}`.trim()}
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function urlBase64ToUint8Array(base64String){const padding='='.repeat((4-base64String.length%4)%4);const base64=(base64String+padding).replace(/-/g,'+').replace(/_/g,'/');const raw=atob(base64);return Uint8Array.from([...raw].map(c=>c.charCodeAt(0)))}
function populateWeeks(){const options=Array.from({length:18},(_,i)=>`<option value="${i+1}">Week ${i+1}</option>`).join('');$('betWeek').innerHTML=options;$('weekFilter').innerHTML=`<option value="all">All Weeks</option>${options}`;$('betWeek').value='1'}
async function updateNotificationStatus(){const el=$('notificationStatus'),btn=$('enableNotificationsBtn');if(!el||!btn)return;if(!('serviceWorker'in navigator)||!('PushManager'in window)||!('Notification'in window)){btn.disabled=true;setMessage(el,'Push notifications are not supported in this browser.','error');return}try{const reg=await navigator.serviceWorker.getRegistration('./');const sub=reg?await reg.pushManager.getSubscription():null;if(sub&&Notification.permission==='granted'){btn.textContent='Hit Alerts Enabled';setMessage(el,'Touchdown alerts are enabled on this device.','success')}else{btn.textContent='Enable Hit Alerts';if(Notification.permission==='denied')setMessage(el,'Notifications are blocked in iPhone Settings for ATD Tracker.','error');else setMessage(el,'Alerts are not enabled on this device.','')}}catch{setMessage(el,'Alerts are not enabled on this device.','')}}
async function enableNotifications(){const btn=$('enableNotificationsBtn'),el=$('notificationStatus');btn.disabled=true;setMessage(el,'Setting up touchdown alerts…');try{if(!('serviceWorker'in navigator)||!('PushManager'in window)||!('Notification'in window))throw new Error('Push notifications are not supported on this device.');const permission=await Notification.requestPermission();if(permission!=='granted')throw new Error('Notification permission was not allowed.');const reg=await navigator.serviceWorker.register('./sw.js');await navigator.serviceWorker.ready;let sub=await reg.pushManager.getSubscription();if(!sub){sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:urlBase64ToUint8Array(VAPID_PUBLIC_KEY)})}const json=sub.toJSON();const{data,error}=await supabase.functions.invoke('atd-push-subscribe',{body:{subscription:{endpoint:json.endpoint,keys:json.keys}}});if(error)throw error;if(data?.error)throw new Error(data.error);const{error:settingsError}=await supabase.from('atd_settings').update({notification_config:json,updated_at:new Date().toISOString()}).eq('user_id',state.user.id);if(settingsError)throw settingsError;state.settings={...state.settings,notification_config:json};btn.textContent='Hit Alerts Enabled';setMessage(el,'Touchdown alerts are enabled on this iPhone.','success')}catch(err){setMessage(el,err.message||'Could not enable notifications.','error')}finally{btn.disabled=false}}
async function init(){populateWeeks();const{data:{session}}=await supabase.auth.getSession();if(session?.user)await enterApp(session.user);else showAuth();supabase.auth.onAuthStateChange(async(_e,s)=>{if(s?.user&&s.user.id!==state.user?.id)await enterApp(s.user);if(!s)showAuth()})}
function showAuth(){state.user=null;authView.classList.remove('hidden');appView.classList.add('hidden')}
async function enterApp(user){state.user=user;authView.classList.add('hidden');appView.classList.remove('hidden');await ensureSettings();await loadBets();scheduleOpenAppRefresh();await updateNotificationStatus()}
async function ensureSettings(){const{data,error}=await supabase.from('atd_settings').select('*').eq('user_id',state.user.id).maybeSingle();if(error)throw error;if(data)state.settings=data;else{const{data:created,error:createError}=await supabase.from('atd_settings').insert({user_id:state.user.id,default_stake:5,season:2026,season_type:2}).select().single();if(createError)throw createError;state.settings=created}$('defaultStake').value=state.settings.default_stake;$('season').value=state.settings.season}
async function loadBets(){const{data,error}=await supabase.from('atd_bets').select('*').order('created_at',{ascending:false});if(error)throw error;state.bets=data||[];renderAll()}
function filteredBets(){const w=$('weekFilter').value;return w==='all'?state.bets:state.bets.filter(b=>String(b.week)===w)}
function renderAll(){renderStats();renderBetList('recentBets',filteredBets().slice(0,6));renderBetList('allBets',state.bets);$('betCount').textContent=`${state.bets.length} total`}
function renderStats(){const bets=filteredBets(),wins=bets.filter(b=>b.result==='Won').length,losses=bets.filter(b=>b.result==='Lost').length,pending=bets.filter(b=>b.result==='Pending').length,staked=bets.reduce((s,b)=>s+Number(b.stake||0),0),potential=bets.reduce((s,b)=>s+potentialProfit(b.stake,b.american_odds),0),pl=bets.reduce((s,b)=>s+Number(b.actual_pl||0),0),graded=bets.filter(b=>['Won','Lost'].includes(b.result)).reduce((s,b)=>s+Number(b.stake||0),0),roi=graded?(pl/graded)*100:0;$('statBets').textContent=bets.length;$('statRecord').textContent=`${wins}-${losses}`;$('statStaked').textContent=money(staked);$('statPotential').textContent=money(potential);$('statPL').textContent=money(pl);$('statPL').className=pl>0?'positive':pl<0?'negative':'';$('statROI').textContent=`${roi.toFixed(1)}%`;$('statROI').className=roi>0?'positive':roi<0?'negative':'';$('statPending').textContent=pending}
function renderBetList(id,bets){const t=$(id);if(!bets.length){t.innerHTML='<div class="empty">No bets yet.</div>';return}t.innerHTML=bets.map(b=>`<article class="bet-card"><div class="bet-top"><div><div class="bet-player">${escapeHtml(b.player_name)}</div><div class="bet-meta">Week ${b.week} · ${escapeHtml(b.team||'—')} vs ${escapeHtml(b.opponent||'—')} · ${dateTime(b.game_date)}</div><div class="bet-meta">${escapeHtml(b.game_status||'Pending')}</div></div><span class="badge ${b.result}">${b.result}</span></div><div class="bet-bottom"><div><span>Odds</span><strong>${odds(b.american_odds)}</strong></div><div><span>Stake</span><strong>${money(b.stake)}</strong></div><div><span>Potential Profit</span><strong>${money(potentialProfit(b.stake,b.american_odds))}</strong></div><div><span>P/L</span><strong class="${Number(b.actual_pl)>0?'positive':Number(b.actual_pl)<0?'negative':''}">${money(b.actual_pl)}</strong></div></div><div class="bet-actions">${b.result==='Pending'&&b.game_id?`<button class="text-btn refresh-one" data-id="${b.id}">Refresh</button>`:''}<button class="text-btn danger delete-bet" data-id="${b.id}">Delete</button></div></article>`).join('')}
async function searchPlayers(q){const{data,error}=await supabase.functions.invoke('atd-nfl',{body:{action:'searchPlayers',query:q}});if(error)throw error;if(data?.error)throw new Error(data.error);return data?.players||[]}
playerInput.addEventListener('input',()=>{state.selectedPlayer=null;selectedPlayerBox.classList.add('hidden');clearTimeout(state.searchTimer);const q=playerInput.value.trim();if(q.length<2){playerResults.classList.add('hidden');playerResults.innerHTML='';return}state.searchTimer=setTimeout(async()=>{try{const players=await searchPlayers(q);playerResults.innerHTML=players.length?players.map(p=>`<button type="button" class="search-item" data-player-id="${escapeHtml(p.playerId)}" data-name="${escapeHtml(p.name)}" data-team="${escapeHtml(p.team)}"><span><strong>${escapeHtml(p.name)}</strong><span>${escapeHtml(p.position||'')}</span></span><strong>${escapeHtml(p.team)}</strong></button>`).join(''):'<div class="empty">No players found.</div>';playerResults.classList.remove('hidden')}catch(e){setMessage(betMessage,e.message||'Player search failed.','error')}},350)});
playerResults.addEventListener('click',e=>{const btn=e.target.closest('.search-item');if(!btn)return;state.selectedPlayer={playerId:btn.dataset.playerId,name:btn.dataset.name,team:btn.dataset.team};playerInput.value=state.selectedPlayer.name;selectedPlayerBox.textContent=`${state.selectedPlayer.name} · ${state.selectedPlayer.team}`;selectedPlayerBox.classList.remove('hidden');playerResults.classList.add('hidden')});
betForm.addEventListener('submit',async e=>{e.preventDefault();setMessage(betMessage,'Looking up matchup…');$('addBetBtn').disabled=true;try{if(!state.selectedPlayer)throw new Error('Choose a player from the search results.');const week=Number($('betWeek').value),americanOdds=Number($('betOdds').value),stakeOverride=$('betStake').value.trim(),stake=stakeOverride===''?Number(state.settings.default_stake):Number(stakeOverride);if(!americanOdds)throw new Error('Enter American odds such as +180 or -110.');if(!Number.isFinite(stake)||stake<=0)throw new Error('Stake must be greater than $0.');const{data:lookup,error:fnError}=await supabase.functions.invoke('atd-nfl',{body:{action:'lookupBet',week,playerName:state.selectedPlayer.name,playerId:state.selectedPlayer.playerId,season:state.settings.season,seasonType:state.settings.season_type}});if(fnError)throw fnError;if(lookup?.error)throw new Error(lookup.error);const payload={user_id:state.user.id,week,player_name:lookup.name,player_id:lookup.playerId,team:lookup.team,opponent:lookup.opponent,game_date:lookup.gameDate,game_id:lookup.gameId,american_odds:americanOdds,stake,result:'Pending',game_status:lookup.gameStatus||'Scheduled'};const{error}=await supabase.from('atd_bets').insert(payload);if(error)throw error;betForm.reset();state.selectedPlayer=null;selectedPlayerBox.classList.add('hidden');$('betWeek').value=String(week);setMessage(betMessage,`${lookup.name}: ${lookup.team} vs ${lookup.opponent} added at ${money(stake)} to win ${money(potentialProfit(stake,americanOdds))}.`,'success');await loadBets()}catch(err){setMessage(betMessage,err.message||'Could not add bet.','error')}finally{$('addBetBtn').disabled=false}});
async function refreshBet(bet){const{data,error}=await supabase.functions.invoke('atd-live',{body:{playerName:bet.player_name,gameId:bet.game_id}});if(error)throw error;if(data?.error)throw new Error(data.error);const{error:updateError}=await supabase.from('atd_bets').update({touchdowns:data.touchdowns,result:data.result,game_status:data.gameStatus,updated_at:new Date().toISOString()}).eq('id',bet.id);if(updateError)throw updateError}
async function refreshPending(){const pending=state.bets.filter(b=>b.result==='Pending'&&b.game_id);if(!pending.length)return;$('refreshBtn').disabled=true;try{for(const bet of pending){try{await refreshBet(bet)}catch(e){console.warn('Refresh failed',bet.player_name,e)}}await loadBets()}finally{$('refreshBtn').disabled=false}}
function scheduleOpenAppRefresh(){clearInterval(window.__atdRefreshTimer);window.__atdRefreshTimer=setInterval(()=>{if(!document.hidden&&state.user)refreshPending()},120000)}
$('refreshBtn').addEventListener('click',refreshPending);
$('weekFilter').addEventListener('change',renderAll);
$('enableNotificationsBtn').addEventListener('click',enableNotifications);
document.addEventListener('click',async e=>{const del=e.target.closest('.delete-bet');if(del){if(!confirm('Delete this bet?'))return;const{error}=await supabase.from('atd_bets').delete().eq('id',del.dataset.id);if(!error)await loadBets()}const ref=e.target.closest('.refresh-one');if(ref){const bet=state.bets.find(b=>b.id===ref.dataset.id);if(bet){await refreshBet(bet);await loadBets()}}});
$('settingsForm').addEventListener('submit',async e=>{e.preventDefault();const payload={default_stake:Number($('defaultStake').value),season:Number($('season').value),updated_at:new Date().toISOString()};const{data,error}=await supabase.from('atd_settings').update(payload).eq('user_id',state.user.id).select().single();if(error)setMessage($('settingsMessage'),error.message,'error');else{state.settings=data;setMessage($('settingsMessage'),'Settings saved.','success')}});
authForm.addEventListener('submit',async e=>{e.preventDefault();setMessage(authMessage,'Signing in…');const{error}=await supabase.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});setMessage(authMessage,error?error.message:'',error?'error':'success')});
$('signupBtn').addEventListener('click',async()=>{setMessage(authMessage,'Creating account…');const{data,error}=await supabase.auth.signUp({email:$('email').value.trim(),password:$('password').value});if(error)return setMessage(authMessage,error.message,'error');setMessage(authMessage,data.session?'Account created.':'Account created. Check your email if confirmation is required.','success')});
$('signOutBtn').addEventListener('click',()=>supabase.auth.signOut());
document.querySelectorAll('.tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t===tab));document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));$(`${tab.dataset.view}View`).classList.remove('hidden')}));
init().catch(err=>setMessage(authMessage,err.message||'Startup failed.','error'));