const SB_URL='https://uinhyjqsqrgfczqrmcya.supabase.co';
const SB_KEY='sb_publishable_qmrBMbSlLInIYT2IXwy49Q_WnMiToQJ';
const hc=window.atdSupabase||window.supabase.createClient(SB_URL,SB_KEY,{auth:{persistSession:true,autoRefreshToken:true}});
let sport='football',hPlayer=null,hTimer=null;window.atdCurrentSport='football';
const q=id=>document.getElementById(id);
function addHockeyUI(){if(q('sportSwitcher'))return;const header=document.querySelector('.app-header');if(!header)return;const sw=document.createElement('div');sw.id='sportSwitcher';sw.innerHTML='<button type="button" data-sport="football" class="sport-tab active">🏈 Football</button><button type="button" data-sport="hockey" class="sport-tab">🏒 Hockey</button>';header.after(sw);const style=document.createElement('style');style.textContent='#sportSwitcher{display:flex;gap:6px;background:#e7e3da;padding:5px;border-radius:14px;margin:0 0 16px}.sport-tab{flex:1;border:0;border-radius:10px;padding:10px 8px;font-weight:800;background:transparent;color:#667085}.sport-tab.active{background:#fff;color:#111827;box-shadow:0 1px 4px #0002}.hockey-only{display:none}.hockey-mode .hockey-only{display:block}.hockey-mode .football-only{display:none}.hockey-fields{display:grid;grid-template-columns:1fr 1fr;gap:10px}.hockey-fields select{width:100%}';document.head.append(style);const form=q('betForm');if(form){const week=q('betWeek')?.closest('label');if(week)week.classList.add('football-only');const td=q('twoTdToggle')?.closest('label');if(td)td.classList.add('football-only');const hf=document.createElement('div');hf.className='hockey-only hockey-fields';hf.innerHTML='<label>Bet Type<select id="hBetType"><option value="point">Point</option><option value="goal">Goal</option><option value="assist">Assist</option></select></label><label>Target<select id="hTarget"><option value="1">1+</option><option value="2">2+</option></select></label>';const player=q('playerInput')?.closest('label');if(player)player.before(hf)}document.querySelectorAll('[data-sport]').forEach(b=>b.addEventListener('click',()=>setSport(b.dataset.sport)));}
function setSport(s){sport=s;window.atdCurrentSport=s;document.body.classList.toggle('hockey-mode',s==='hockey');document.querySelectorAll('.sport-tab').forEach(b=>b.classList.toggle('active',b.dataset.sport===s));hPlayer=null;if(q('playerInput'))q('playerInput').value='';q('selectedPlayer')?.classList.add('hidden');const title=document.querySelector('.app-header h1'),eye=document.querySelector('.app-header .eyebrow'),tag=document.querySelector('.header-tagline'),slip=document.querySelector('#betsView .add-card h2'),logeye=document.querySelector('#betsView .subpage-head .eyebrow');if(title)title.textContent=s==='hockey'?'Hockey Tracker':'TD Tracker';if(eye)eye.textContent=s==='hockey'?'NHL Betting Log':'NFL Betting Log';if(tag)tag.textContent=s==='hockey'?'Track every goal, assist and point.':'Make every TD count.';if(slip)slip.textContent=s==='hockey'?'Player Prop':'Anytime TD';if(logeye)logeye.textContent=s==='hockey'?'NHL Betting Log':'NFL Betting Log';loadSportBets();}
async function loadSportBets(){const{data}=await hc.from('atd_bets').select('*').order('created_at',{ascending:false});const list=(data||[]).filter(b=>(b.sport||'football')===sport);if(typeof state!=='undefined'){state.bets=list;renderAll()}if(typeof bets!=='undefined'){bets=list;try{renderWeeklyReview();renderExtras();decorateBetRows()}catch{}}}
async function hSearch(text){const{data,error}=await hc.functions.invoke('atd-nhl',{body:{action:'searchPlayers',query:text}});if(error)throw error;if(data?.error)throw new Error(data.error);return data.players||[]}
document.addEventListener('input',e=>{if(sport!=='hockey'||e.target?.id!=='playerInput')return;e.stopImmediatePropagation();hPlayer=null;clearTimeout(hTimer);const text=e.target.value.trim(),host=q('playerResults');if(text.length<2){host.classList.add('hidden');return}hTimer=setTimeout(async()=>{try{const ps=await hSearch(text);host.innerHTML=ps.length?ps.map(p=>`<button type="button" class="search-item" data-hid="${p.playerId}" data-hname="${p.name}" data-hteam="${p.team}"><span><strong>${p.name}</strong><span>${p.position||''}</span></span><strong>${p.team||''}</strong></button>`).join(''):'<div class="empty">No NHL players found.</div>';host.classList.remove('hidden')}catch(err){q('betMessage').textContent=err.message}},250)},true);
document.addEventListener('click',e=>{if(sport!=='hockey')return;const b=e.target.closest('[data-hid]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();hPlayer={playerId:b.dataset.hid,name:b.dataset.hname,team:b.dataset.hteam};q('playerInput').value=hPlayer.name;q('selectedPlayer').textContent=`${hPlayer.name} · ${hPlayer.team}`;q('selectedPlayer').classList.remove('hidden');q('playerResults').classList.add('hidden')},true);
document.addEventListener('submit',async e=>{if(sport!=='hockey'||e.target?.id!=='betForm')return;e.preventDefault();e.stopImmediatePropagation();const msg=q('betMessage'),btn=q('addBetBtn');try{if(!hPlayer)throw new Error('Choose an NHL player from the search results.');btn.disabled=true;msg.textContent='Looking up NHL matchup…';const odds=Number(q('betOdds').value),stake=q('betStake').value?Number(q('betStake').value):Number(state?.settings?.default_stake||5),type=q('hBetType').value,target=Number(q('hTarget').value);if(!odds)throw new Error('Enter American odds.');const{data,error}=await hc.functions.invoke('atd-nhl',{body:{action:'lookupBet',playerId:hPlayer.playerId,playerName:hPlayer.name,season:20262027}});if(error)throw error;if(data?.error)throw new Error(data.error);const payload={user_id:state.user.id,sport:'hockey',week:0,player_name:data.name,player_id:data.playerId,team:data.team,opponent:data.opponent,game_date:data.gameDate,game_id:data.gameId,american_odds:odds,stake,bet_type:type,stat_target:target,current_stat:0,result:'Pending',game_status:data.gameStatus||'Scheduled'};const{error:ins}=await hc.from('atd_bets').insert(payload);if(ins)throw ins;q('betForm').reset();hPlayer=null;q('selectedPlayer').classList.add('hidden');msg.textContent=`${data.name}: ${target}+ ${type} added · ${data.team} vs ${data.opponent}`;await loadSportBets();setTimeout(()=>document.querySelector('#betsBackBtn')?.click(),500)}catch(err){msg.textContent=err.message||'Could not add hockey bet.'}finally{btn.disabled=false}},true);
addHockeyUI();setTimeout(addHockeyUI,500);window.atdSetSport=setSport;
