const pbClient=window.atdSupabase||window.supabase.createClient('https://uinhyjqsqrgfczqrmcya.supabase.co','sb_publishable_qmrBMbSlLInIYT2IXwy49Q_WnMiToQJ',{auth:{persistSession:true,autoRefreshToken:true}});
const pb$=id=>document.getElementById(id);
const pbEscape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pbOdds=v=>{const n=Number(v);return Number.isFinite(n)?`${n>0?'+':''}${n}`:''};
const pbDate=v=>v?new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZone:'America/New_York'}).format(new Date(v)):'—';
function pbProp(b){const t=String(b.bet_type||'point').toLowerCase(),n=t==='goal'?'G':t==='assist'?'A':'P';return `${Number(b.stat_target||1)}+ ${n}`}
function installParlayBuilder(){if(pb$('parlayBuilderModal'))return;const style=document.createElement('style');style.textContent=`
.hockey-mode .parlay-builder-btn{display:inline-flex}.parlay-builder-btn{display:none;border:1px solid #9fcbd9;background:#fff;color:#006b91;border-radius:10px;padding:8px 11px;font-size:13px;font-weight:900}.parlay-modal{position:fixed;inset:0;z-index:1000;background:rgba(4,28,44,.55);display:flex;align-items:flex-end;justify-content:center;padding:0}.parlay-modal.hidden{display:none}.parlay-sheet{width:min(680px,100%);max-height:88vh;overflow:auto;background:#f7fbfd;border-radius:22px 22px 0 0;padding:18px 16px calc(18px + env(safe-area-inset-bottom));box-shadow:0 -14px 40px #00182740}.parlay-sheet-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:5px}.parlay-sheet-head h2{margin:0;color:#062f4f}.parlay-close{border:0;background:#e4f1f6;color:#174b64;border-radius:50%;width:36px;height:36px;font-size:22px}.parlay-intro{margin:0 0 13px;color:#647f8e;font-size:13px}.parlay-picks{display:grid;gap:8px}.parlay-pick{display:grid;grid-template-columns:26px 1fr auto;align-items:center;gap:10px;padding:11px;border:1px solid #c6dfe8;background:#fff;border-radius:13px}.parlay-pick input{width:20px;height:20px;accent-color:#007ea8}.parlay-pick-main{min-width:0}.parlay-pick-main strong{display:block;color:#12394d;font-size:14px}.parlay-pick-main span{display:block;color:#718794;font-size:12px;margin-top:2px}.parlay-pick-prop{font-weight:900;color:#006f96;font-size:13px;text-align:right}.parlay-fields{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:14px}.parlay-fields label{font-size:12px;font-weight:900;color:#476878}.parlay-fields input{display:block;width:100%;height:48px;margin-top:5px;border:1px solid #b9d5df;border-radius:11px;padding:0 12px;background:#fff;font-size:16px;font-weight:800}.parlay-create{width:100%;margin-top:12px;border:0;border-radius:13px;padding:15px;background:#062f4f;color:#fff;font-size:16px;font-weight:900}.parlay-builder-msg{min-height:18px;margin:9px 2px 0;font-size:13px;font-weight:800}.parlay-builder-msg.error{color:#b42318}.parlay-builder-msg.success{color:#087a5b}.parlay-empty{padding:18px;text-align:center;background:#fff;border:1px solid #c6dfe8;border-radius:13px;color:#708697}
`;document.head.append(style);const modal=document.createElement('div');modal.id='parlayBuilderModal';modal.className='parlay-modal hidden';modal.innerHTML=`<div class="parlay-sheet"><div class="parlay-sheet-head"><div><p class="eyebrow">Hockey</p><h2>Parlay Builder</h2></div><button type="button" class="parlay-close" id="parlayBuilderClose">×</button></div><p class="parlay-intro">Select 2 or more pending single props. The original single bets stay unchanged and can be reused in other parlays.</p><div id="parlayBuilderPicks" class="parlay-picks"></div><div class="parlay-fields"><label>Parlay Odds<input id="parlayBuilderOdds" type="text" inputmode="text" placeholder="+450"></label><label>Parlay Stake<input id="parlayBuilderStake" type="number" min="0.01" step="0.01" inputmode="decimal" placeholder="$10"></label></div><button type="button" id="parlayBuilderCreate" class="parlay-create">Create Parlay</button><p id="parlayBuilderMsg" class="parlay-builder-msg"></p></div>`;document.body.append(modal);ensureBuilderButton()}
function ensureBuilderButton(){if(window.atdCurrentSport!=='hockey')return;const head=document.querySelector('#myBetsPanel .dash-section .dash-section-head');if(!head||pb$('parlayBuilderBtn'))return;const refresh=pb$('refreshBtn'),btn=document.createElement('button');btn.id='parlayBuilderBtn';btn.type='button';btn.className='parlay-builder-btn';btn.textContent='＋ Parlay Builder';if(refresh)head.insertBefore(btn,refresh);else head.append(btn)}
async function openBuilder(){const host=pb$('parlayBuilderPicks'),msg=pb$('parlayBuilderMsg');msg.textContent='Loading pending props…';msg.className='parlay-builder-msg';pb$('parlayBuilderModal').classList.remove('hidden');const{data:{session}}=await pbClient.auth.getSession();if(!session){msg.textContent='Sign in again to build a parlay.';msg.className+=' error';return}const{data,error}=await pbClient.from('atd_bets').select('id,player_name,team,opponent,game_date,american_odds,bet_type,stat_target,result,wager_type,sport').eq('user_id',session.user.id).eq('sport','hockey').eq('result','Pending').eq('wager_type','single').order('game_date',{ascending:true});if(error){msg.textContent=error.message;msg.className+=' error';return}const list=data||[];host.innerHTML=list.length?list.map(b=>`<label class="parlay-pick"><input type="checkbox" data-parlay-bet="${b.id}"><span class="parlay-pick-main"><strong>${pbEscape(b.player_name)}</strong><span>${pbEscape(b.team||'—')} vs ${pbEscape(b.opponent||'—')} · ${pbDate(b.game_date)} · Single ${pbOdds(b.american_odds)}</span></span><span class="parlay-pick-prop">${pbProp(b)}</span></label>`).join(''):'<div class="parlay-empty">No pending single Hockey props are available.</div>';msg.textContent=''}
async function createParlay(){const msg=pb$('parlayBuilderMsg'),btn=pb$('parlayBuilderCreate'),ids=[...document.querySelectorAll('[data-parlay-bet]:checked')].map(x=>x.dataset.parlayBet),odds=Number(pb$('parlayBuilderOdds').value),stake=Number(pb$('parlayBuilderStake').value);if(ids.length<2){msg.textContent='Select at least 2 pending props.';msg.className='parlay-builder-msg error';return}if(!odds||!stake||stake<=0){msg.textContent='Enter valid parlay odds and stake.';msg.className='parlay-builder-msg error';return}btn.disabled=true;btn.textContent='Creating…';try{const{data:{session}}=await pbClient.auth.getSession();if(!session)throw new Error('Sign in again to continue.');const{data:valid,error:ve}=await pbClient.from('atd_bets').select('id').eq('user_id',session.user.id).eq('sport','hockey').eq('result','Pending').eq('wager_type','single').in('id',ids);if(ve)throw ve;if((valid||[]).length!==ids.length)throw new Error('One of those props is no longer pending. Reopen the builder.');const{data:p,error:pe}=await pbClient.from('atd_parlays').insert({user_id:session.user.id,sport:'hockey',american_odds:odds,stake,result:'Pending'}).select('id').single();if(pe)throw pe;const legs=ids.map((bet_id,i)=>({parlay_id:p.id,bet_id,leg_number:i+1}));const{error:le}=await pbClient.from('atd_parlay_legs').insert(legs);if(le){await pbClient.from('atd_parlays').delete().eq('id',p.id);throw le}msg.textContent=`Created ${ids.length}-leg parlay. You can immediately build another from the same singles.`;msg.className='parlay-builder-msg success';document.querySelectorAll('[data-parlay-bet]:checked').forEach(x=>x.checked=false);pb$('parlayBuilderOdds').value='';pb$('parlayBuilderStake').value='';window.atdRefreshDashboard?.()}catch(e){msg.textContent=e.message||'Could not create parlay.';msg.className='parlay-builder-msg error'}finally{btn.disabled=false;btn.textContent='Create Parlay'}}
document.addEventListener('click',e=>{if(e.target.closest('#parlayBuilderBtn')){openBuilder();return}if(e.target.closest('#parlayBuilderClose')||e.target===pb$('parlayBuilderModal')){pb$('parlayBuilderModal')?.classList.add('hidden');return}if(e.target.closest('#parlayBuilderCreate'))createParlay();if(e.target.closest('[data-sport]'))setTimeout(ensureBuilderButton,120)});
const pbObserver=new MutationObserver(()=>ensureBuilderButton());
function pbStart(){installParlayBuilder();const panel=pb$('myBetsPanel');if(panel)pbObserver.observe(panel,{childList:true,subtree:true});setTimeout(ensureBuilderButton,400)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',pbStart);else pbStart();
