(function(){
const SB=()=>window.atdSupabase;
const money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(v||0));
const odds=v=>{const n=Number(v);return Number.isFinite(n)?`${n>0?'+':''}${n}`:''};
const pp=(s,o)=>Number(o)>0?Number(s||0)*Number(o)/100:Number(s||0)*100/Math.abs(Number(o)||1);
const dt=v=>v?new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZone:'America/New_York'}).format(new Date(v)):'—';
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const start=v=>{const t=new Date(v||0).getTime();return Number.isFinite(t)&&t>0?t:Number.MAX_SAFE_INTEGER};
function card(b){return `<div class="swipe-bet" data-id="${b.id}"><div class="swipe-delete" aria-hidden="true">Delete</div><div class="swipe-content"><details class="dash-bet"><summary><div class="dash-bet-main"><strong>${esc(b.player_name)}</strong><span>${esc(b.team||'—')} vs ${esc(b.opponent||'—')} · ${odds(b.american_odds)}${Number(b.touchdown_target||1)===2?' · 2 TD':''}</span><span class="dash-game-time">${dt(b.game_date)}</span></div><div class="dash-bet-right"><span class="badge ${b.result}">${b.result}</span><span class="dash-chevron">›</span></div></summary><div class="dash-bet-detail"><div><span>Week</span><strong>${b.week}</strong></div><div><span>Stake</span><strong>${money(b.stake)}</strong></div><div><span>Potential</span><strong>${money(pp(b.stake,b.american_odds))}</strong></div><div><span>P/L</span><strong class="${Number(b.actual_pl)>0?'positive':Number(b.actual_pl)<0?'negative':''}">${money(b.actual_pl)}</strong></div><p>${dt(b.game_date)} · ${esc(b.game_status||'Pending')}</p>${b.result!=='Pending'&&b.result!=='Void'?`<button type="button" class="text-btn refund-bet" data-id="${b.id}">Mark Refunded</button>`:''}</div></details></div></div>`}
async function renderFootballOnly(){if((window.atdCurrentSport||'football')!=='football')return;const c=SB();if(!c)return;const week=document.getElementById('weekFilter')?.value||'all';let query=c.from('atd_bets').select('*').or('sport.eq.football,sport.is.null').order('created_at',{ascending:false});if(week!=='all')query=query.eq('week',Number(week));const{data,error}=await query;if(error)return;const list=data||[];for(const [id,pending] of [['pendingBets',true],['finishedBets',false]]){const host=document.getElementById(id);if(!host)continue;let rows=list.filter(b=>pending?b.result==='Pending':b.result!=='Pending');if(pending)rows=rows.slice().sort((a,b)=>start(a.game_date)-start(b.game_date));host.innerHTML=rows.length?rows.map(card).join(''):`<div class="dashboard-empty">No ${pending?'pending':'finished'} bets.</div>`;}
window.setTimeout(()=>{document.querySelectorAll('.dash-bet').forEach(row=>{const name=row.querySelector('.dash-bet-main strong')?.textContent?.trim(),b=list.find(x=>x.player_name===name);if(!b||!b.player_id)return;const main=row.querySelector('.dash-bet-main');if(!main||main.closest('.dash-player-wrap'))return;const wrap=document.createElement('div');wrap.className='dash-player-wrap';const img=document.createElement('img');img.className='player-photo';img.alt=`${b.player_name} headshot`;img.loading='lazy';img.src=`https://sleepercdn.com/content/nfl/players/${encodeURIComponent(b.player_id)}.jpg`;img.onerror=()=>{img.onerror=null;img.style.display='none'};main.parentNode.insertBefore(wrap,main);wrap.append(img,main)})},0)}
document.addEventListener('click',e=>{if(e.target.closest('[data-sport="football"]'))setTimeout(renderFootballOnly,250)});document.getElementById('weekFilter')?.addEventListener('change',()=>setTimeout(renderFootballOnly,50));document.addEventListener('visibilitychange',()=>{if(!document.hidden)setTimeout(renderFootballOnly,250)});setInterval(renderFootballOnly,30000);window.atdRenderFootballOnly=renderFootballOnly;
})();